name: Discord Bot Deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *' # Runs every 2 hours

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17'

    - name: Install dependencies
      run: |
        npm install

    - name: Kill existing bot processes
      run: |
        # Find the process ID of the bot
        PID=$(pgrep -f bot.mjs)
        # If the bot is running, kill it
        if [ -n "$PID" ]; then
          echo "Killing existing bot process with PID: $PID"
          kill -9 $PID
        fi

    - name: Run bot
      run: |
        node bot.mjs
      env:
        token: ${{ secrets.dctoken }}
